version: '3.8'

services:
  magic-api:
    image: ghcr.io/magic-tn/magic-api:latest
    container_name: magic-api
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - MODE=dev
      - STORAGES_POSTGRESQL_HOST=postgres
      - STORAGES_POSTGRESQL_PORT=5432
      - STORAGES_POSTGRESQL_MAGICDB=magicdb
      - STORAGES_POSTGRESQL_MAGICLOGIN=admin
      - STORAGES_POSTGRESQL_MAGICPASS=magic-api
    networks:
      - magic-network

  postgres:
    image: postgres:15-alpine
    container_name: magic-api-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=magicdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=magic-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - magic-network

networks:
  magic-network:
    driver: bridge

volumes:
  postgres_data:
