services:
  postgresdb:
    container_name: postgresdb
    image: postgres:15-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=magic-api
      - POSTGRES_USER=postgres
      # variables used by init script:
      - MAGIC_DB=magicdb
      - MAGIC_USER=admin
      - MAGIC_PASS=magic-api
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
