#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	-- Create user if not exists
	DO \$\$
	BEGIN
		IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$MAGIC_USER') THEN
			CREATE USER $MAGIC_USER WITH PASSWORD '$MAGIC_PASS';
		ELSE
			ALTER USER $MAGIC_USER WITH PASSWORD '$MAGIC_PASS';
		END IF;
	END
	\$\$;

	-- Create database if not exists
	SELECT 'CREATE DATABASE $MAGIC_DB WITH OWNER $MAGIC_USER ENCODING="UTF8" LC_COLLATE="en_US.utf8" LC_CTYPE="en_US.utf8"'
	WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$MAGIC_DB')\gexec

	-- Grant all privileges on database
	GRANT ALL PRIVILEGES ON DATABASE $MAGIC_DB TO $MAGIC_USER;

	-- Connect to the database and grant schema permissions
	\c $MAGIC_DB
	
	-- Grant all privileges on all tables in the public schema
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $MAGIC_USER;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $MAGIC_USER;
	GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $MAGIC_USER;
	
	-- Set default privileges for future objects
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $MAGIC_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $MAGIC_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $MAGIC_USER;
EOSQL
