
storages:
  # user & database should have been created by container or deployment.
    - name: pg-magic-api
      enabled: true
      driver: pg
      dbURI: ""
      schemaFolder: "file:///migrations/pg/magic"
      forceSchemaVersion: 1