storages:
  - name: pg-magic-api
    enabled: true
    driver: pg
    dbURI: "postgresql://admin:magic-api@localhost:5435/magicdb?sslmode=disable"
    schemaFolder: "file://migrations/pg/magic"
    forceSchemaVersion: 1
